poses:
  wave:
    - hand_1: 
        motor_ids:
        - 0
        - 1
        - 2
        position:
        - 1500
        - 1500
        - 1500
    - hand_2: 
        motor_ids:
        - 0
        - 1
        - 2
        position:
        - 1500
        - 1500
        - 1500
    - hand_3: 
        motor_ids:
        - 0
        - 1
        - 2
        position:
        - 1500
        - 1500
        - 1500
